/**
 * Created by dat on 22/09/2016.
 */

const images = {
    profile: require('../images/handsome_shuai.png'),
    bird: require('../images/turnup_bird.png'),
    email: require('../images/email.png'),
    password: require('../images/password.png'),
    trollface: require('../images/handsome_shuai.png'),
    host_logo: require('../images/host_logo.png'),
    man_logo: require('../images/man_logo.png'),
    guitar_logo: require('../images/guitar_logo.png'),
    book_logo: require('../images/book_logo.png'),
    basketball_logo: require('../images/basketball_logo.png'),
    filter_logo: require('../images/filter_logo.png'),
    beer_logo: require('../images/beer-logo.png'),
    beer_1: require('../images/Beer8.png'),
    beer_6: require('../images/Beer9.png'),
    beer_7: require('../images/Beer10.png'),
    beer_8: require('../images/Beer11.png'),
    beer_9: require('../images/Beer12.png'),
    beer_10: require('../images/Beer11.png'),
    beer_2: require('../images/Beer2.png'),
    beer_3: require('../images/Beer3.png'),
    beer_4: require('../images/Beer4.png'),
    beer_5: require('../images/Beer5.png'),
    facebook_login: require('../images/facebook_login.png'),
    google_login: require('../images/google-login-logo.png'),

    location_pin: require('../images/location.png'),
    clock: require('../images/clock.png'),
    calendar: require('../images/calendar.png'),
    location_pin_selected: require('../images/location_selected.png'),
    clock_selected: require('../images/clock_selected.png'),
    calendar_selected: require('../images/calendar_selected.png'),
    enrichment_back: require('../images/enrichment_back.png'),
    enrichment_rocket: require('../images/enrichment_rocket.png'),

    explore_logo: require('../images/explore_logo.png'),
    hosted_logo: require('../images/hosted_logo.png'),
    surprise_logo: require('../images/surprise_logo.png'),
    sports_1_logo: require('../images/Sports1.png'),
    sports_2_logo: require('../images/Sports2.png'),
    sports_3_logo: require('../images/Sports3.png'),
    book_1: require('../images/Book1.png'),
    book_2: require('../images/Book3.png'),
    music_1: require('../images/Music1.png'),
    music_2: require('../images/Music2.png'),
    summary_title: require('../images/Summary.png'),
    turnup_title: require('../images/TurnUp_White.png'),
    summary_plus: require('../images/plus.png'),
    summary_eye: require('../images/eye.png'),
    back: require('../images/BACK.png'),
    summary_edit: require('../images/Edit Button.png'),
    turnup_bird_button: require('../images/turnup_bird_button.png'),
    summary_preview: require('../images/Preview.png'),
    summary_turnup_button: require('../images/TurnUpBUtton.png'),
    event_1: require('../images/event_1.png'),
    event_2: require('../images/event_2.png'),
    event_3: require('../images/Concert_Explore.png'),
    event_4: require('../images/Sports_Explore.png'),
    forward: require('../images/FORWARD.png'),
    google_map: require('../images/Google-Map.png'),

    summary_input: require('../images/summary_input.png'),
    summary_location: require('../images/summary_location.png'),
    summary_top: require('../images/summary_top.png'),

    datetimeplus: require('../images/datetimeplus.png'),
    creation_back: require('../images/creation_back.png'),
    creation_next: require('../images/creation_next.png'),
    chosen_timings_label: require('../images/chosen_timings_label.png'),
    clear_date_time: require('../images/clear_date_time.png'),
    progress_common_availability: require('../images/progress_common_avail.png'),

    progress_map: require('../images/OneMoreToGo.png'),
    my_event: require('../images/MyEventImage.png'),
    search_logo: require('../images/SearchIcon.png'),
    droppin_logo: require('../images/dropPin.png'),
    creation_later: require('../images/creation_later.png'),

    banner_rocket: require('../images/banner_rocket.png'),
    banner_food: require('../images/banner_food.png'),
    map_icon: require('../images/Map_Icon.png'),
    common_availability_label: require('../images/common_availability_label.png'),
    rsvp_summary_label: require('../images/rsvp_summary_label.png'),
    invite_more: require('../images/invite_more.png'),
    highest_attendance_banner: require('../images/Highest_Attendance_Banner.png'),
    pick_green: require('../images/Pick_Green.png'),
    pick_grey: require('../images/Pick_Grey.png'),

    message_logo: require('../images/MessageIcon.png'),
    unticked_box: require('../images/untickedBox.png'),
    ticked_box: require('../images/tickedBox.png'),

    calendar_icon: require('../images/Calendar_Icon.png'),
    inactive_calendar_tab: require('../images/calendar_grey.png'),
    inactive_location_tab: require('../images/dropPin_grey.png'),
    inactive_summary_tab: require('../images/TurnUp_grey.png'),
    summary_icon: require('../images/summary_tab_icon.png'),
    creation_invite: require('../images/creation_invite.png'),

    send_to_label: require('../images/send_to_label.png'),
    creation_done: require('../images/creation_done.png'),

    dashboard_label: require('../images/Dashboard_Label.png'),
    edit_label: require('../images/EditLabel.png'),
    done_label: require('../images/Done_Label.png'),
};


export default images;